theme = "wolf-alabaster-dark"

[editor]
bufferline = 'always'
cursorline = true
true-color = true
color-modes = true

[editor.file-picker]
hidden = true

[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
A-d = [':buffer-close']
A-left = [':buffer-previous']
A-right = [':buffer-next'] 

[keys.insert]
A-d = [':buffer-close']
A-left = [':buffer-previous']
A-right = [':buffer-next'] 
A-backspace = 'normal_mode'
C-backspace = 'delete_word_backward'

[editor.lsp]
auto-signature-help = false
