theme = "gruvbox_original_dark_medium"

[editor]
shell = ['fish']
bufferline = 'always' 

[editor.file-picker]
hidden = false

[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[editor.lsp]
auto-signature-help = false
