theme = "wolf-alabaster-dark"

[editor]
bufferline = 'always'
cursorline = true
true-color = true
color-modes = true

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding","version-control", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = "|"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = true

[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
A-d = [':buffer-close']
A-left = [':buffer-previous']
A-right = [':buffer-next'] 
C-g = [':new', ':insert-output lazygit', ':buffer-close!', ':redraw']

[keys.insert]
A-d = [':buffer-close']
A-left = [':buffer-previous']
A-right = [':buffer-next'] 
A-backspace = 'normal_mode'
C-backspace = 'delete_word_backward'

[editor.lsp]
auto-signature-help = false
display-messages = true
