[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.discord-rpc]
command = "discord-rpc-lsp"

[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-ls",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = [
  "vscode-css-language-server",
  "tailwindcss-ls",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
# auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
# auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
# auto-format = true

[[language]]
name = "svelte"
language-servers = [
  "svelteserver",
  "tailwindcss-ls",
  "discord-rpc"
]

[[language]]
name = "c"
language-servers = ["clangd", "discord-rpc"]
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "discord-rpc"]
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "go"
language-servers = ["gopls", "discord-rpc"]
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "discord-rpc"]
